### ISSUE TITLE
Is (n *Node) Remove(ichild INode) safe for frequent use?

### ISSUE THREAD

**Issue by FluorescentTouch** [g3n/engine#204]
I have an App, that updates 3d models every time interval. Outdated ones removed from scene using App.Scene().Remove(), new one added with Add(). 
For small update time intervals (about 100ms) i often receive this kind of panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x4e5313]

goroutine 1 [running, locked to thread]:
github.com/g3n/engine/core.(*Node).UpdateMatrixWorld(0xc003b6a640)
        /home/sgaratuev/go/pkg/mod/github.com/g3n/engine@v0.1.0/core/node.go:758 +0xb3
github.com/g3n/engine/core.(*Node).UpdateMatrixWorld(0xc0001d6280)
        /home/sgaratuev/go/pkg/mod/github.com/g3n/engine@v0.1.0/core/node.go:758 +0xbd
github.com/g3n/engine/renderer.(*Renderer).renderScene(0xc000128600, 0x6c27c0, 0xc0001d6280, 0x6c1c40, 0xc00000c5a0, 0x56, 0x57)
        /home/sgaratuev/go/pkg/mod/github.com/g3n/engine@v0.1.0/renderer/renderer.go:181 +0x4c
github.com/g3n/engine/renderer.(*Renderer).Render(0xc000128600, 0x6c1c40, 0xc00000c5a0, 0x0, 0x0, 0xb9ec00)
        /home/sgaratuev/go/pkg/mod/github.com/g3n/engine@v0.1.0/renderer/renderer.go:161 +0x120
github.com/g3n/engine/util/application.(*Application).Run(0xc0001d6140, 0x0, 0x0)
        /home/sgaratuev/go/pkg/mod/github.com/g3n/engine@v0.1.0/util/application/application.go:471 +0x2e6
hurricane/draw.(*Drawer).Run(...)
        /home/sgaratuev/my/hurricane/draw/draw.go:84
main.main()
        /home/sgaratuev/my/hurricane/main.go:78 +0xbab
```

May this panic caused by frequent Remove() calls, since both methods (n *Node) UpdateMatrixWorld()  and (n *Node) Remove(ichild INode) works with node children without any mutexes?

**Comment by FluorescentTouch** [comment]
For some reason, code snippet does not work

**Comment by FluorescentTouch** [comment]
Actually problem was rotating scene via mouse, while hundreds of event happening simultaneously.
And i don't know the reason.
Gonna fix this with disabling interaction with scene while in progress.
