### ISSUE TITLE
[bug] incorrect preprocessor directive

### ISSUE THREAD

**Issue by Raphy42** [g3n/engine#79]
`g3n/engine commit: 1947ea87d4dc4603f0ecb3e14aadbcdee649c839`

Hello, I have a `glsl` compilation error whenever I try the latest version of `g3n/g3nd` or the sample application `g3n/demos/hellog3n`.
I've not yet tested previous version of the engine but it seems related to the recent modifications of the glsl bone directives.
```
OS: 64bit Mac OS X 10.13.6 17G65
Kernel: x86_64 Darwin 17.7.0
GPU: Intel Iris Pro / NVIDIA GeForce GT 750M
```

I'm currently looking into it and but it might take me some time to make a working PR.
I'm using a modified version of the `g3n/demos/hello3gn` where I added an error check to `app.Run()`
```
$ go run main.go 
13:39:14.317947:I::OpenGL version: 4.1 NVIDIA-10.32.0 355.11.10.10.40.102
panic: error compiling Vertex Shader: ERROR: 0:84: '' : syntax error: incorrect preprocessor directive
ERROR: 0:84: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:128: '' : syntax error: incorrect preprocessor directive
ERROR: 0:128: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:131: '' : syntax error: incorrect preprocessor directive
ERROR: 0:131: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:133: '' : syntax error: incorrect preprocessor directive
ERROR: 0:133: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:135: '' : syntax error: incorrect preprocessor directive
ERROR: 0:135: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
001:#version 330 core
002:#define AMB_LIGHTS 1
003:#define DIR_LIGHTS 0
004:#define POINT_LIGHTS 1
005:#define SPOT_LIGHTS 0
006:#define MAT_TEXTURES 0
007://
008:// Vertex Shader
009://
010:
011://
012:// Vertex attributes
013://
014:layout(location = 0) in  vec3  VertexPosition;
015:layout(location = 1) in  vec3  VertexNormal;
016:layout(location = 2) in  vec3  VertexColor;
017:layout(location = 3) in  vec2  VertexTexcoord;
018:layout(location = 4) in  float VertexDistance;
019:layout(location = 5) in  vec4  VertexTexoffsets;
020:
021:
022:// Model uniforms
023:uniform mat4 ModelViewMatrix;
024:uniform mat3 NormalMatrix;
025:uniform mat4 MVP;
026:
027:
028://
029:// Material properties uniform
030://
031:
032:// Material parameters uniform array
033:uniform vec3 Material[6];
034:// Macros to access elements inside the Material array
035:#define MatAmbientColor             Material[0]
036:#define MatDiffuseColor     Material[1]
037:#define MatSpecularColor    Material[2]
038:#define MatEmissiveColor    Material[3]
039:#define MatShininess        Material[4].x
040:#define MatOpacity          Material[4].y
041:#define MatPointSize        Material[4].z
042:#define MatPointRotationZ   Material[5].x
043:
044:#if MAT_TEXTURES > 0
045:    // Texture unit sampler array
046:    uniform sampler2D MatTexture[MAT_TEXTURES];
047:    // Texture parameters (3*vec2 per texture)
048:    uniform vec2 MatTexinfo[3*MAT_TEXTURES];
049:    // Macros to access elements inside the MatTexinfo array
050:    #define MatTexOffset(a)         MatTexinfo[(3*a)]
051:    #define MatTexRepeat(a)         MatTexinfo[(3*a)+1]
052:    #define MatTexFlipY(a)          bool(MatTexinfo[(3*a)+2].x)
053:    #define MatTexVisible(a)        bool(MatTexinfo[(3*a)+2].y)
054:#endif
055:
056:// GLSL 3.30 does not allow indexing texture sampler with non constant values.
057:// This macro is used to mix the texture with the specified index with the material color.
058:// It should be called for each texture index. It uses two externally defined variables:
059:// vec4 texColor
060:// vec4 texMixed
061:#define MIX_TEXTURE(i)                                                                       \
062:    if (MatTexVisible(i)) {                                                                  \
063:        texColor = texture(MatTexture[i], FragTexcoord * MatTexRepeat(i) + MatTexOffset(i)); \
064:        if (i == 0) {                                                                        \
065:            texMixed = texColor;                                                             \
066:        } else {                                                                             \
067:            texMixed = mix(texMixed, texColor, texColor.a);                                  \
068:        }                                                                                    \
069:    }
070:
071:// TODO for alpha blending dont use mix use implementation below (similar to one in panel shader)
072:            //vec4 prevTexPre = texMixed;                                                      \
073:            //prevTexPre.rgb *= prevTexPre.a;                                                  \
074:            //vec4 currTexPre = texColor;                                                      \
075:            //currTexPre.rgb *= currTexPre.a;                                                  \
076:            //texMixed = currTexPre + prevTexPre * (1 - currTexPre.a);                         \
077:            //texMixed.rgb /= texMixed.a;
078:
079:#ifdef MORPHTARGETS
080:    uniform float morphTargetInfluences[MORPHTARGETS];
081:    
082:#endif
083:
084:#if BONE_INFLUENCERS > 0
085:    uniform mat4 mBones[TOTAL_BONES];
086:    in vec4 matricesIndices;
087:    in vec4 matricesWeights;
088://    #if BONE_INFLUENCERS > 4
089://        in vec4 matricesIndicesExtra;
090://        in vec4 matricesWeightsExtra;
091://    #endif
092:#endif
093:// Output variables for Fragment shader
094:out vec4 Position;
095:out vec3 Normal;
096:out vec3 CamDir;
097:out vec2 FragTexcoord;
098:
099:void main() {
100:
101:    // Transform this vertex position to camera coordinates.
102:    Position = ModelViewMatrix * vec4(VertexPosition, 1.0);
103:
104:    // Transform this vertex normal to camera coordinates.
105:    Normal = normalize(NormalMatrix * VertexNormal);
106:
107:    // Calculate the direction vector from the vertex to the camera
108:    // The camera is at 0,0,0
109:    CamDir = normalize(-Position.xyz);
110:
111:    // Flips texture coordinate Y if requested.
112:    vec2 texcoord = VertexTexcoord;
113:#if MAT_TEXTURES>0
114:    if (MatTexFlipY(0)) {
115:        texcoord.y = 1 - texcoord.y;
116:    }
117:#endif
118:    FragTexcoord = texcoord;
119:    vec3 vPosition = VertexPosition;
120:    mat4 finalWorld = mat4(1.0);
121:    
122:#ifdef MORPHTARGETS
123:
124:    
125:
126:#endif
127:
128:#if BONE_INFLUENCERS > 0
129:
130:    mat4 influence = mBones[int(matricesIndices[0])] * matricesWeights[0];
131:    #if BONE_INFLUENCERS > 1
132:        influence += mBones[int(matricesIndices[1])] * matricesWeights[1];
133:        #if BONE_INFLUENCERS > 2
134:            influence += mBones[int(matricesIndices[2])] * matricesWeights[2];
135:            #if BONE_INFLUENCERS > 3
136:                influence += mBones[int(matricesIndices[3])] * matricesWeights[3];
137://                #if BONE_INFLUENCERS > 4
138://                    influence += mBones[int(matricesIndicesExtra[0])] * matricesWeightsExtra[0];
139://                    #if BONE_INFLUENCERS > 5
140://                        influence += mBones[int(matricesIndicesExtra[1])] * matricesWeightsExtra[1];
141://                        #if BONE_INFLUENCERS > 6
142://                            influence += mBones[int(matricesIndicesExtra[2])] * matricesWeightsExtra[2];
143://                            #if BONE_INFLUENCERS > 7
144://                                influence += mBones[int(matricesIndicesExtra[3])] * matricesWeightsExtra[3];
145://                            #endif
146://                        #endif
147://                    #endif
148://                #endif
149:            #endif
150:        #endif
151:    #endif
152:
153:    finalWorld = finalWorld * influence;
154:
155:#endif
156:gl_Position = MVP * finalWorld * vec4(vPosition, 1.0);
157:}
158:
159:


goroutine 1 [running, locked to thread]:
main.check(0x4229520, 0xc420010aa0)
        /Users/rdantzer/GO/src/github.com/raphy42/playground/main.go:14 +0x4a
main.main()
        /Users/rdantzer/GO/src/github.com/raphy42/playground/main.go:45 +0x2c6
exit status 2
```

**Comment by amyadzuki** [comment]
I think it can't handle the spaces surrounding the `>` character.

**Comment by danaugrs** [comment]
It could be because BONE_INFLUENCERS is not being defined. In my preprocessor that probably resolves to 0 but in others it may not.

**Comment by amyadzuki** [comment]
OH YEAH!  Good catch!  Try this then, a trick I learned from C: `(BONE_INFLUENCERS - 0)`

**Comment by danaugrs** [comment]
I added a `#ifdef BONE_INFLUENCERS` wrapping those shader chunks (https://github.com/g3n/engine/commit/b7cc1e54cdcf07a259332283cabf0dce5764b233) - please get latest and let us know if it works!

**Comment by danaugrs** [comment]
Wouldn't `(BONE_INFLUENCERS - 0)` fail similarly as BONE_INFLUENCERS isn't defined?

**Comment by amyadzuki** [comment]
If it isn't defined then it evaluates to `( - 0)` which is integral negative zero.

**Comment by Raphy42** [comment]
[b7cc1e5](https://github.com/g3n/engine/commit/b7cc1e54cdcf07a259332283cabf0dce5764b233) does the trick for me, I can see the blue torus!

**Comment by danaugrs** [comment]
@Raphy42 Wonderful!
@amyadzuki I see 😄
